%% Part 2: import the PyTorch MLP for weight inspection
% The imported network is a weight source only and is not the reference.

clearvars
rng("default")

scriptPath = mfilename("fullpath");
repoRoot = fileparts(fileparts(fileparts(scriptPath)));
resultsRoot = fullfile(repoRoot, "agentic_ai", "results");
modelPath = fullfile(repoRoot, "Part_2_AI_import", "models", ...
    "mlp_soc_model.pt2");

assert(isfile(modelPath), "PyTorch model was not found: %s", modelPath);
if ~isfolder(resultsRoot)
    mkdir(resultsRoot);
end

netImport = importNetworkFromPyTorch(modelPath);
if ~netImport.Initialized
    inputLayer = featureInputLayer(5, Normalization="none", Name="input_1");
    netImport = addInputLayer(netImport, inputLayer, Initialize=true);
end
netImport = expandLayers(netImport);

layerNames = strings(numel(netImport.Layers), 1);
layerClasses = strings(numel(netImport.Layers), 1);
possiblyUnsupported = false(numel(netImport.Layers), 1);
for layerIndex = 1:numel(netImport.Layers)
    layerNames(layerIndex) = string(netImport.Layers(layerIndex).Name);
    layerClasses(layerIndex) = string(class(netImport.Layers(layerIndex)));
    possiblyUnsupported(layerIndex) = contains(layerClasses(layerIndex), ...
        ["PlaceholderLayer", "pytorch", "autogenerated"], IgnoreCase=true);
end
layerInventory = table((1:numel(netImport.Layers)).', layerNames, ...
    layerClasses, possiblyUnsupported, VariableNames=["Index", "Layer", ...
    "Class", "PossiblyUnsupported"]);

learnableLayer = string(netImport.Learnables.Layer);
learnableParameter = string(netImport.Learnables.Parameter);
learnableSize = strings(height(netImport.Learnables), 1);
for learnableIndex = 1:height(netImport.Learnables)
    learnableSize(learnableIndex) = mat2str( ...
        size(netImport.Learnables.Value{learnableIndex}));
end
learnableInventory = table(learnableLayer, learnableParameter, ...
    learnableSize, VariableNames=["Layer", "Parameter", "Size"]);

writetable(layerInventory, fullfile(resultsRoot, ...
    "part2_imported_layer_inventory.csv"));
writetable(learnableInventory, fullfile(resultsRoot, ...
    "part2_imported_learnable_inventory.csv"));
save(fullfile(resultsRoot, "part2_imported_network.mat"), "netImport");

disp(layerInventory)
disp(learnableInventory)
fprintf("IMPORTED_NETWORK_CLASS=%s\n", class(netImport));
fprintf("IMPORTED_NETWORK_INITIALIZED=%d\n", netImport.Initialized);
fprintf("IMPORTED_LAYER_COUNT=%d\n", numel(netImport.Layers));
fprintf("IMPORTED_LEARNABLE_COUNT=%d\n", height(netImport.Learnables));
fprintf("IMPORTED_POSSIBLY_UNSUPPORTED_COUNT=%d\n", ...
    sum(possiblyUnsupported));
fprintf("PYTORCH_IMPORT_INSPECTION_GATE=PASS\n");
